name: Github - Activity - Readme

on:
	- cron: "0 " " " ""
	workflow_dispatch:
 
 	jobs:
		builds:
			runs-on: ubuntu-latest
			
			steps:
				- uses: actions/checkout@v2
				- uses: Merytek/github-activity-readme@master
					env:
						GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
